// Code generated by protoc-gen-go. DO NOT EDIT.
// source: httpqueue.proto

package protobufs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HttpApiQueueItem_HttpApiQueueItemType int32

const (
	HttpApiQueueItem_NEW_JOURNAL    HttpApiQueueItem_HttpApiQueueItemType = 0
	HttpApiQueueItem_SAVE_JOURNAL   HttpApiQueueItem_HttpApiQueueItemType = 1
	HttpApiQueueItem_DELETE_JOURNAL HttpApiQueueItem_HttpApiQueueItemType = 2
)

var HttpApiQueueItem_HttpApiQueueItemType_name = map[int32]string{
	0: "NEW_JOURNAL",
	1: "SAVE_JOURNAL",
	2: "DELETE_JOURNAL",
}

var HttpApiQueueItem_HttpApiQueueItemType_value = map[string]int32{
	"NEW_JOURNAL":    0,
	"SAVE_JOURNAL":   1,
	"DELETE_JOURNAL": 2,
}

func (x HttpApiQueueItem_HttpApiQueueItemType) String() string {
	return proto.EnumName(HttpApiQueueItem_HttpApiQueueItemType_name, int32(x))
}

func (HttpApiQueueItem_HttpApiQueueItemType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5a79479ce9e34b39, []int{1, 0}
}

type HttpApiQueue struct {
	Queue                []*HttpApiQueueItem `protobuf:"bytes,1,rep,name=queue,proto3" json:"queue,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *HttpApiQueue) Reset()         { *m = HttpApiQueue{} }
func (m *HttpApiQueue) String() string { return proto.CompactTextString(m) }
func (*HttpApiQueue) ProtoMessage()    {}
func (*HttpApiQueue) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a79479ce9e34b39, []int{0}
}

func (m *HttpApiQueue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpApiQueue.Unmarshal(m, b)
}
func (m *HttpApiQueue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpApiQueue.Marshal(b, m, deterministic)
}
func (m *HttpApiQueue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpApiQueue.Merge(m, src)
}
func (m *HttpApiQueue) XXX_Size() int {
	return xxx_messageInfo_HttpApiQueue.Size(m)
}
func (m *HttpApiQueue) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpApiQueue.DiscardUnknown(m)
}

var xxx_messageInfo_HttpApiQueue proto.InternalMessageInfo

func (m *HttpApiQueue) GetQueue() []*HttpApiQueueItem {
	if m != nil {
		return m.Queue
	}
	return nil
}

type HttpApiQueueItem struct {
	Type                 HttpApiQueueItem_HttpApiQueueItemType `protobuf:"varint,1,opt,name=type,proto3,enum=protobufs.HttpApiQueueItem_HttpApiQueueItemType" json:"type,omitempty"`
	Params               map[string]string                     `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *HttpApiQueueItem) Reset()         { *m = HttpApiQueueItem{} }
func (m *HttpApiQueueItem) String() string { return proto.CompactTextString(m) }
func (*HttpApiQueueItem) ProtoMessage()    {}
func (*HttpApiQueueItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a79479ce9e34b39, []int{1}
}

func (m *HttpApiQueueItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpApiQueueItem.Unmarshal(m, b)
}
func (m *HttpApiQueueItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpApiQueueItem.Marshal(b, m, deterministic)
}
func (m *HttpApiQueueItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpApiQueueItem.Merge(m, src)
}
func (m *HttpApiQueueItem) XXX_Size() int {
	return xxx_messageInfo_HttpApiQueueItem.Size(m)
}
func (m *HttpApiQueueItem) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpApiQueueItem.DiscardUnknown(m)
}

var xxx_messageInfo_HttpApiQueueItem proto.InternalMessageInfo

func (m *HttpApiQueueItem) GetType() HttpApiQueueItem_HttpApiQueueItemType {
	if m != nil {
		return m.Type
	}
	return HttpApiQueueItem_NEW_JOURNAL
}

func (m *HttpApiQueueItem) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

func init() {
	proto.RegisterEnum("protobufs.HttpApiQueueItem_HttpApiQueueItemType", HttpApiQueueItem_HttpApiQueueItemType_name, HttpApiQueueItem_HttpApiQueueItemType_value)
	proto.RegisterType((*HttpApiQueue)(nil), "protobufs.HttpApiQueue")
	proto.RegisterType((*HttpApiQueueItem)(nil), "protobufs.HttpApiQueueItem")
	proto.RegisterMapType((map[string]string)(nil), "protobufs.HttpApiQueueItem.ParamsEntry")
}

func init() { proto.RegisterFile("httpqueue.proto", fileDescriptor_5a79479ce9e34b39) }

var fileDescriptor_5a79479ce9e34b39 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcf, 0x28, 0x29, 0x29,
	0x28, 0x2c, 0x4d, 0x2d, 0x4d, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x04, 0x53, 0x49,
	0xa5, 0x69, 0xc5, 0x4a, 0x8e, 0x5c, 0x3c, 0x1e, 0x40, 0x59, 0xc7, 0x82, 0xcc, 0x40, 0x90, 0x02,
	0x21, 0x43, 0x2e, 0x56, 0xb0, 0x4a, 0x09, 0x46, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x69, 0x3d, 0xb8,
	0x52, 0x3d, 0x64, 0x75, 0x9e, 0x25, 0xa9, 0xb9, 0x41, 0x10, 0x95, 0x4a, 0x8b, 0x99, 0xb8, 0x04,
	0xd0, 0xe5, 0x84, 0x5c, 0xb8, 0x58, 0x4a, 0x2a, 0x0b, 0x40, 0xc6, 0x30, 0x6a, 0xf0, 0x19, 0x19,
	0xe0, 0x31, 0x06, 0x43, 0x20, 0x04, 0xa8, 0x2f, 0x08, 0xac, 0x5b, 0xc8, 0x9e, 0x8b, 0xad, 0x20,
	0xb1, 0x28, 0x31, 0xb7, 0x58, 0x82, 0x09, 0xec, 0x1c, 0x75, 0x7c, 0xe6, 0x04, 0x80, 0x55, 0xba,
	0xe6, 0x95, 0x14, 0x55, 0x06, 0x41, 0xb5, 0x49, 0x59, 0x72, 0x71, 0x23, 0x09, 0x0b, 0x09, 0x70,
	0x31, 0x67, 0xa7, 0x56, 0x82, 0x1d, 0xc5, 0x19, 0x04, 0x62, 0x0a, 0x89, 0x70, 0xb1, 0x96, 0x25,
	0xe6, 0x00, 0xfd, 0xcb, 0x04, 0x16, 0x83, 0x70, 0xac, 0x98, 0x2c, 0x18, 0x95, 0x7c, 0xb9, 0x44,
	0xb0, 0xb9, 0x4c, 0x88, 0x9f, 0x8b, 0xdb, 0xcf, 0x35, 0x3c, 0xde, 0xcb, 0x3f, 0x34, 0xc8, 0xcf,
	0xd1, 0x47, 0x80, 0x01, 0x68, 0x28, 0x4f, 0xb0, 0x63, 0x98, 0x2b, 0x5c, 0x84, 0x51, 0x48, 0x88,
	0x8b, 0xcf, 0xc5, 0xd5, 0xc7, 0x35, 0x04, 0x21, 0xc6, 0x94, 0xc4, 0x06, 0x76, 0xb9, 0x31, 0x20,
	0x00, 0x00, 0xff, 0xff, 0x33, 0x2c, 0xe9, 0xa0, 0x8d, 0x01, 0x00, 0x00,
}
